tasks:
  - init: >
      pip3 install -r ./requirements.txt
  - command: >
      python3 setup.py develop
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-python.python@2020.1.58038:pjpQRQV8ZYUJkihlvnRPDQ==
    - formulahendry.code-runner@0.9.15:WUpvbF4Wg44WiaFa7exZBw==