language: python
python:
  - "2.7"
# command to run tests
script: pytest
notifications:
  slack:
    rooms:
      - loksu:jErzuILLSNn9qGYkkILvBwje#general
      - loksu:jErzuILLSNn9qGYkkILvBwje#random